### PR TITLE
Make props & state observable in constructor & componentWillMount

### LINKED ISSUE #478: reactions do not work over props when used in constructor, but they work when used in componentDidMount
React 16.3, latest mobx-react

Today I found a weird issue when I was creating a reaction over props in the component constructor (using TS btw):
```
@observer
class MyC extends React.Component {
  constructor(props) {
    super(props);
    this.r = reaction(() => this.props.open, () => {
      // for some reason this would only run once, but never again when the this.props.open changed
    }, { fireImmediately: true });
  }
}
```

however when I moved the reaction to componentDidMount it all started working...

makes me wonder, maybe react is internally making a copy of the props and swapping them before componentDidMount executes?

or maybe props made observable after the constructor runs?
if so then maybe the decorator should override the super class constructor function and inject the make observable thing on it?

### PR DESCRIPTION
**Pull request by Strate**
Moved instrumentation of state & props to `observer` decorator.
Closes #478

### CODE REVIEW

File: src/observer.js [hunk 1]
```diff
@@ -177,17 +157,12 @@ function makeComponentReactive(render) {
      * If props are shallowly modified, react will render anyway,
      * so atom.reportChanged() should not result in yet another re-render
      */
-    let skipRender = false
+    this[skipRenderKey] = false
```
Comment (mweststrate) [inline src/observer.js]: could we make this a non-enumerable prop?

File: src/observer.js [hunk 2]
```diff
@@ -177,17 +157,12 @@ function makeComponentReactive(render) {
...
      * forceUpdate will re-assign this.props. We don't want that to cause a loop,
      * so detect these changes
      */
-    let isForcingUpdate = false
-
-    // make this.props an observable reference, see #124
-    makePropertyObservableReference.call(this, "props")
-    // make state an observable reference
-    makePropertyObservableReference.call(this, "state")
+    this[isForcingUpdateKey] = false
```
Comment (mweststrate) [inline src/observer.js]: idem

File: src/observer.js [hunk 3]
```diff
@@ -273,6 +248,32 @@ const reactiveMixin = {
     }
 }
 
+function makeObservableProp(target, propName) {
+    const valueHolderKey = Symbol(propName + " value holder")
+    const atomHolderKey = Symbol(propName + " atom holder")
+    function getAtom() {
+        return this[atomHolderKey] || (this[atomHolderKey] = createAtom("reactive " + propName))
```
Comment (mweststrate) [inline src/observer.js]: could we make this a non-enumerable prop?

File: src/observer.js (hunk 1 above)
Comment (Strate) [reply src/observer.js]: I think yes, of course

File: src/observer.js (hunk 2 above)
Comment (Strate) [reply src/observer.js]: Please clarify, dont understood :(

File: src/observer.js [hunk 4]
```diff
@@ -273,6 +248,32 @@ const reactiveMixin = {
     }
 }
 
+function makeObservableProp(target, propName) {
+    const valueHolderKey = Symbol(propName + " value holder")
+    const atomHolderKey = Symbol(propName + " atom holder")
```
Comment (mweststrate) [inline src/observer.js]: I am wondering whether using Symbols is a breaking change. So far we didn't depend on them, but I think React itself already requires Symbol or a polyfill of it? (Since mobx-react 5 can still be used with mobx 4 so should work on any ES 5 env)

File: src/observer.js (hunk 3 above)
Comment (Strate) [reply src/observer.js]: Yes. Will address this a bit later today.

**Comment by mweststrate** [comment]
Looks like a great improvement! Left some questions

File: src/observer.js (hunk 4 above)
Comment (Strate) [reply src/observer.js]: I will check this out, maybe there is a way to do this without symbols.

File: src/observer.js (hunk 2 above)
Comment (mweststrate) [reply src/observer.js]: Sorry, making this a non-enumerable prop as well :)

File: src/observer.js (hunk 4 above)
Comment (xaviergonz) [reply src/observer.js]: The support looks pretty good to me: https://caniuse.com/#search=symbol

Comment (mweststrate) [reply src/observer.js]: without symbols it could be done by putting an object under some ugly key. Symbols is preferred though :) You could always create a super naive polyfill like: `function Symbol(name) { return `$mobxReactProp${symbolname}${Math.random()} }`. But since react itself already requires quite some polyfills ([link](https://reactjs.org/docs/javascript-environment-requirements.html]) I think we can bet on Symbol to be present. And otherwise fix it if somebody reports is

**Comment by Strate** [comment]
Made internal props hidden, but keep Symbol as is.

**Comment by mweststrate** [comment]
Merging! Will release soon :-)

**Comment by Strate** [comment]
Wow, cool! Can't wait for release :)

**Comment by mweststrate** [comment]
Released as 5.2.1!

**Comment by TomaszGrzelak** [comment]
@mweststrate - Sadly I've just run into a problem that is 90% likely to be connected with the changes discussed here (got 5.2.1 installed just a few hours ago).
What I found, is that `Symbol` is not natively supported on Android (using React-Native).
I managed to get things working by adding `import 'es6-symbol/implement';` at the very beginning of my index.js file.

**Comment by Strate** [comment]
@TomaszGrzelak oh, sorry for that. I gonna to make PR to naive polyfill Symbol

**Comment by Strate** [comment]
@TomaszGrzelak #499
