### PR TITLE
Issue #839: Re-add isMobXReactObserver property and perform check on class components

### LINKED ISSUE #839: Re-add `isMobXReactObserver` property on class components
Hey guys, 

I'm running into a stack overflow and not sure what to make of it.  Making an issue here in case it happens to evolve into something.  

Ends up in the endless reactive render cycle.  Maybe allowStateChanges is the culprit here, or more like I'm doing something wrong?  Maybe both?  

For limited context, I have a page with a container (which is an observer) with easily hundreds of child containers (which are also observers) and where each child container has multiple labels (also observers).  

The browser logs state that the overflow is coming from `Label.render()`, but might be deceptive.  Started noticing it after upgrading to v6, but can't say if it's the actually cause.  

Going to try downgrading to 5 in attempts to isolate, and will update here.  And/or trying to reproduce this with minimal noise that shareable.

Happy to provide more context within limits, just let me know.  

```
(anonymous) (mobx-react.umd-6.1.4.js:formatted:189)
trackDerivedFunction (mobx.umd-5.14.2.js:766)
Reaction.track (mobx.umd-5.14.2.js:1794)
u (mobx-react.umd-6.1.4.js:formatted:187)
(anonymous) (mobx-react.umd-6.1.4.js:formatted:201)
r.render (mobx-react.umd-6.1.4.js:formatted:203)
allowStateChanges (mobx.umd-5.14.2.js:976)
(anonymous) (mobx-react.umd-6.1.4.js:formatted:189)
trackDerivedFunction (mobx.umd-5.14.2.js:766)
Reaction.track (mobx.umd-5.14.2.js:1794)
u (mobx-react.umd-6.1.4.js:formatted:187)
(anonymous) (mobx-react.umd-6.1.4.js:formatted:201)
r.render (mobx-react.umd-6.1.4.js:formatted:203)
allowStateChanges (mobx.umd-5.14.2.js:976)
(anonymous) (mobx-react.umd-6.1.4.js:formatted:189)
trackDerivedFunction (mobx.umd-5.14.2.js:766)
Reaction.track (mobx.umd-5.14.2.js:1794)
u (mobx-react.umd-6.1.4.js:formatted:187)
(anonymous) (mobx-react.umd-6.1.4.js:formatted:201)
r.render (mobx-react.umd-6.1.4.js:formatted:203)
allowStateChanges (mobx.umd-5.14.2.js:976)
(anonymous) (mobx-react.umd-6.1.4.js:formatted:189)
trackDerivedFunction (mobx.umd-5.14.2.js:766)
Reaction.track (mobx.umd-5.14.2.js:1794)
u (mobx-react.umd-6.1.4.js:formatted:187)
(anonymous) (mobx-react.umd-6.1.4.js:formatted:201)
r.render (mobx-react.umd-6.1.4.js:formatted:203)
finishClassComponent (react-dom.development-16.11.0.js:18597)
updateClassComponent (react-dom.development-16.11.0.js:18550)
beginWork$1 (react-dom.development-16.11.0.js:20307)
beginWork$$1 (react-dom.development-16.11.0.js:25860)
performUnitOfWork (react-dom.development-16.11.0.js:24808)
workLoopSync (react-dom.development-16.11.0.js:24784)
performSyncWorkOnRoot (react-dom.development-16.11.0.js:24383)
(anonymous) (react-dom.development-16.11.0.js:12326)
unstable_runWithPriority (react.development-16.11.0.js:3096)
runWithPriority$2 (react-dom.development-16.11.0.js:12276)
flushSyncCallbackQueueImpl (react-dom.development-16.11.0.js:12321)
flushSyncCallbackQueue (react-dom.development-16.11.0.js:12309)
batchedUpdates$1 (react-dom.development-16.11.0.js:24505)
reactionScheduler (mobx.umd-5.14.2.js:1904)
runReactions (mobx.umd-5.14.2.js:1880)
endBatch (mobx.umd-5.14.2.js:1580)
_endAction (mobx.umd-5.14.2.js:965)
executeAction (mobx.umd-5.14.2.js:919)
res (mobx.umd-5.14.2.js:904)
(anonymous) (PageStore.ts:179)
finished (PageStore.ts:179)
```

### PR DESCRIPTION
**Pull request by ynejati**
Fixes #839 
 
-   [x] Added/updated unit tests
-   [x] Updated changelog
-   [ ] Updated `README` if applicable

### CODE REVIEW

**Comment by ynejati** [comment]
Updated the change log.  Going to need to actually increment the version, potentially add tests, and update the Readme.  Looking for guidance on what you'd like me to do.  Should have marked it as a draft PR, but can't backtrack, so going to mark as WIP for now.

**Comment by FredyC** [comment]
Do not need to bump version, will happen in a release process.

I would probably wrap both of those code blocks to `__DEV__` check as we don't this in production.

Adding test good idea for sure and to tweak the on that is broken as well.

**Comment by ynejati** [comment]
Good point.  Also, something just realized, if the render of a parent class
is a reaction as a result of observer and that subclass overrides the
render of the parent, the render is no longer reactive.

**Comment by ynejati** [comment]
Okay, I see now.  Regarding a subclass who extends a parent class and overrides the parents reactive render.  This behavior is not supported.  The subclass will need to re-declare itself as an observer.  That is fair.  Curious, what happens to the reaction of the parent class.  Is it leaked?

File: src/observerClass.ts [hunk 1]
```diff
@@ -52,14 +63,7 @@ export function makeClassComponentObserver(
...
         if (isUsingStaticRendering() === true) return
-        if (this.render[mobxAdminProperty]) {
-            this.render[mobxAdminProperty].dispose()
-        } else if (__DEV__) {
-            const displayName = getDisplayName(this)
-            console.warn(
-                `The render function for an observer component (${displayName}) was modified after MobX attached. This is not supported, since the new function can't be triggered by MobX.`
-            )
-        }
+        this.render[mobxAdminProperty] && this.render[mobxAdminProperty].dispose()
```
Comment (FredyC) [inline src/observerClass.ts]:
```suggestion
        this.render[mobxAdminProperty]?.dispose()
```

File: src/observerClass.ts [hunk 2]
```diff
@@ -20,11 +21,22 @@ export function makeClassComponentObserver(
...
-        );
-        return componentClass;
+
+    if (__DEV__) {
+        if (componentClass[mobxObserverProperty] && this.render[mobxAdminProperty]) {
+            console.warn(
+                `The provided component class (${getDisplayName(this)}) is already an observer component.`
+            );
+            return componentClass;
+        } else if (componentClass[mobxObserverProperty]) {
```
Comment (FredyC) [inline src/observerClass.ts]: So this block replaces the one you have deleted down below? Just making sure I understand it correctly.

File: src/observerClass.ts (hunk 1 above)
Comment (ynejati) [reply src/observerClass.ts]: Yep, I'm planning on submitting a PR in the lite repo.

File: src/observerClass.ts (hunk 2 above)
Comment (ynejati) [reply src/observerClass.ts]: Moves the reactive render check out of the `componentWilllUnmount` block and also performs the `isMobXReactObserve` check, all in one block.  I'll remove the WIP label in my next push, still working things out.

**Comment by ynejati** [comment]
Decided to keep it simple, and just log a warning instead of performing some hand holding.  I haven't heard anyone else complain about the removal of the `isMobxReactObserver` string property, so we went with symbol or string util.  Going to do a similar check in the lite lib next.

File: src/observerClass.ts [hunk 3]
```diff
@@ -20,6 +21,19 @@ export function makeClassComponentObserver(
...
+
+    if (__DEV__) {
+        if (componentClass[mobxObserverProperty]) {
+            const displayName = getDisplayName(this)
+            console.warn(
+                `The provided component class (${displayName}) 
+                 has already been declared as an observer component.`
+            )
+        } else if (!componentClass[mobxObserverProperty]) {
+            componentClass[mobxObserverProperty] = true
```
Comment (mweststrate) [inline src/observerClass.ts:33]: I'd do the assignment also outside `__DEV__` environments; I can imagine people might somehow attach behavior to it, and get caught unaware in production

**Comment by FredyC** [comment]
@ynejati Are you willing to continue on this PR?

File: src/observerClass.ts (hunk 3 above)
Comment (ynejati) [reply src/observerClass.ts:33]: Okay, cool.  That aligns with my original thought.

**Comment by ynejati** [comment]
@FredyC, yep.  Sorry, been MIA.  These last couple of months have been weird.

**Comment by FredyC** [comment]
Please update the size limit config to `4.1 kB`. Also, some tests are failing.

**Comment by ynejati** [comment]
Bummer.  Okay.

**Comment by ynejati** [comment]
I'll fix the tests, but just so you know they are also broken on the master.

**Comment by FredyC** [comment]
Oh! That's interesting. For a while, I thought it's some failure on Coveralls side. Only now when I saw failed test-size I checked the other one too.

If you have a time for it I would certainly appreciate if you can fix those.

**Comment by ynejati** [comment]
@FredyC, this thing is ready when you get a chance.  Thanks, man.

File: package.json [hunk 4]
```diff
@@ -90,7 +90,7 @@
     "typescript": "^3.7.0"
   },
   "dependencies": {
-    "mobx-react-lite": "2"
+    "mobx-react-lite": "2.0.6"
```
Comment (FredyC) [inline package.json:93]: Why depend on a specific version? I would rather not as it would be releasing a new version of this package when lite gets updated. If anything, it should be `>=2.0.6`.

Comment (ynejati) [reply package.json]: Valid question. I misinterpreted 2 to be a specific version and not a range

**Comment by FredyC** [comment]
Thanks a lot, that was somewhat painful PR given how little it is :)

File: src/observerClass.ts [hunk 5]
```diff
@@ -20,6 +21,17 @@ export function makeClassComponentObserver(
     componentClass: React.ComponentClass<any, any>
 ): React.ComponentClass<any, any> {
     const target = componentClass.prototype
+
+    if (componentClass[mobxObserverProperty]) {
+        const displayName = getDisplayName(this)
```
Comment (FredyC) [inline src/observerClass.ts:26]: @ynejati Looks like the issue #887 is related to this change. What is the idea behind using `this` in here?

Comment (mweststrate) [reply src/observerClass.ts:26]: This can't be correct, as `this` isn't bound at this (lol) point, `I think `componentClass.displayName || componentClass.name` will do the trick here

Comment (mweststrate) [reply src/observerClass.ts:26]: In Javascript `"strict"` mode this will die hard iirc

Comment (ynejati) [reply src/observerClass.ts:26]: Well, that's silly.  Surprised that it's taken this long to catch it.  How embarrassing.  I guess the test failed to catch it as well.  I will submit a PR  later today if someone doesn't get to it before me.

Comment (ynejati) [reply src/observerClass.ts:26]: `target` seems to work too

Comment (ynejati) [reply src/observerClass.ts:26]: Test output before (using `this`):

image

Test output after (using `target`):

image
